# Generated by Django 4.1.3 on 2024-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_stock"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="description",),
        migrations.AlterField(
            model_name="product", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product", name="stock", field=models.IntegerField(),
        ),
    ]
